# Generated by Django 3.2.15 on 2022-08-30 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_myapp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
