# Generated by Django 3.2.15 on 2022-08-30 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_myapp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='date',
            field=models.DateField(blank=True, default=datetime.date),
        ),
    ]
