# Generated by Django 3.2.15 on 2022-08-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_myapp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
